FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app
COPY backend/requirements/ requirements/
COPY ml/ /opt/ml/
RUN pip install --no-cache-dir -r requirements/development.txt -e /opt/ml
COPY backend/ .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
