# Generated by Django 5.2.17 on 2026-08-18 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bakim', '0002_arizaparcakurali_gerekli_miktar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArizaTipiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(choices=[('TWF', 'TWF'), ('HDF', 'HDF'), ('PWF', 'PWF'), ('OSF', 'OSF')], max_length=3)),
                ('olasilik', models.FloatField()),
                ('threshold', models.FloatField()),
                ('esik_asildi', models.BooleanField()),
                ('guven_durumu', models.CharField(max_length=32, null=True)),
                ('operasyonel_kullanima_uygun', models.BooleanField()),
                ('guvenilir_aday', models.BooleanField()),
                ('siralama', models.PositiveSmallIntegerField(null=True)),
                ('base_value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tahmin_ariza_tipi_snapshotlari',
                'ordering': ('siralama', 'kod'),
            },
        ),
        migrations.CreateModel(
            name='TahminKaydi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_id', models.CharField(max_length=64)),
                ('kaynak', models.CharField(choices=[('MANUEL', 'Manuel'), ('REPLAY', 'Replay'), ('ENTEGRASYON', 'Entegrasyon')], max_length=12)),
                ('olcum_zamani', models.DateTimeField()),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('makine_kodu_snapshot', models.CharField(max_length=50)),
                ('makine_adi_snapshot', models.CharField(max_length=150)),
                ('kritiklik_snapshot', models.PositiveSmallIntegerField()),
                ('sensor_snapshot', models.JSONField()),
                ('risk_orani', models.FloatField()),
                ('risk_uyarisi', models.BooleanField()),
                ('binary_threshold', models.FloatField()),
                ('binary_model_version', models.CharField(max_length=100)),
                ('binary_pipeline_version', models.CharField(max_length=50)),
                ('failure_type_durum', models.CharField(max_length=32)),
                ('failure_type_model_version', models.CharField(max_length=100, null=True)),
                ('failure_type_pipeline_version', models.CharField(max_length=50, null=True)),
                ('belirsiz_fiziksel_tip', models.BooleanField()),
                ('aciklanabilirlik_durum', models.CharField(max_length=32)),
                ('binary_base_value', models.FloatField(null=True)),
                ('makine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahmin_kayitlari', to='bakim.makine')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahmin_kayitlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tahmin_kayitlari',
                'ordering': ('-olcum_zamani', '-olusturulma_zamani', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ShapEtkisiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedef', models.CharField(max_length=32)),
                ('sira', models.PositiveSmallIntegerField()),
                ('feature', models.CharField(max_length=100)),
                ('gorunen_ad', models.CharField(max_length=150)),
                ('original_feature_value', models.JSONField()),
                ('model_feature_value', models.FloatField()),
                ('birim', models.CharField(max_length=20, null=True)),
                ('shap_value', models.FloatField()),
                ('yon', models.CharField(max_length=20)),
                ('ariza_tipi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shap_etkileri', to='tahminler.arizatipisnapshot')),
                ('tahmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shap_etkileri', to='tahminler.tahminkaydi')),
            ],
            options={
                'db_table': 'tahmin_shap_snapshotlari',
                'ordering': ('hedef', 'sira'),
            },
        ),
        migrations.CreateModel(
            name='ErpSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parca_kodu_snapshot', models.CharField(max_length=50)),
                ('parca_adi_snapshot', models.CharField(max_length=150)),
                ('gerekli_miktar', models.PositiveIntegerField()),
                ('toplam_stok', models.PositiveIntegerField()),
                ('kullanilabilir_stok', models.PositiveIntegerField()),
                ('minimum_stok', models.PositiveIntegerField()),
                ('tedarik_gun', models.PositiveIntegerField()),
                ('stok_yeterli', models.BooleanField()),
                ('deneysel', models.BooleanField()),
                ('onerilen_aksiyon_snapshot', models.TextField()),
                ('ariza_tipi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_snapshotlari', to='tahminler.arizatipisnapshot')),
                ('parca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahmin_erp_snapshotlari', to='bakim.parca')),
                ('tahmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erp_snapshotlari', to='tahminler.tahminkaydi')),
            ],
            options={
                'db_table': 'tahmin_erp_snapshotlari',
                'ordering': ('ariza_tipi__siralama', 'parca_kodu_snapshot'),
            },
        ),
        migrations.AddField(
            model_name='arizatipisnapshot',
            name='tahmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ariza_tipleri', to='tahminler.tahminkaydi'),
        ),
        migrations.AddConstraint(
            model_name='tahminkaydi',
            constraint=models.UniqueConstraint(fields=('makine', 'kaynak', 'idempotency_key'), name='tahmin_idempotency_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='tahminkaydi',
            constraint=models.CheckConstraint(condition=models.Q(('risk_orani__gte', 0), ('risk_orani__lte', 1)), name='tahmin_risk_0_1'),
        ),
        migrations.AddConstraint(
            model_name='tahminkaydi',
            constraint=models.CheckConstraint(condition=models.Q(('binary_threshold__gte', 0), ('binary_threshold__lte', 1)), name='tahmin_threshold_0_1'),
        ),
        migrations.AddConstraint(
            model_name='tahminkaydi',
            constraint=models.CheckConstraint(condition=models.Q(('kritiklik_snapshot__gte', 1), ('kritiklik_snapshot__lte', 5)), name='tahmin_kritiklik_1_5'),
        ),
        migrations.AddConstraint(
            model_name='shapetkisisnapshot',
            constraint=models.UniqueConstraint(fields=('tahmin', 'hedef', 'sira'), name='tahmin_shap_sira_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='shapetkisisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('sira__gte', 1)), name='tahmin_shap_sira_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.UniqueConstraint(fields=('tahmin', 'ariza_tipi', 'parca'), name='tahmin_erp_parca_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('gerekli_miktar__gt', 0)), name='tahmin_erp_miktar_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='arizatipisnapshot',
            constraint=models.UniqueConstraint(fields=('tahmin', 'kod'), name='tahmin_ariza_kodu_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='arizatipisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('olasilik__gte', 0), ('olasilik__lte', 1)), name='ariza_olasilik_0_1'),
        ),
        migrations.AddConstraint(
            model_name='arizatipisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__gte', 0), ('threshold__lte', 1)), name='ariza_threshold_0_1'),
        ),
    ]
