# Generated by Django 5.2.17 on 2026-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakim', '0002_arizaparcakurali_gerekli_miktar_and_more'),
        ('tahminler', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('toplam_stok__gte', 0)), name='tahmin_erp_toplam_negatif_degil'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('kullanilabilir_stok__gte', 0)), name='tahmin_erp_kullanilabilir_negatif_degil'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stok__gte', 0)), name='tahmin_erp_minimum_negatif_degil'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('tedarik_gun__gte', 0)), name='tahmin_erp_tedarik_negatif_degil'),
        ),
    ]
