# Generated by Django 5.2.17 on 2026-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakim', '0002_arizaparcakurali_gerekli_miktar_and_more'),
        ('tahminler', '0002_erpsnapshot_tahmin_erp_toplam_negatif_degil_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='erpsnapshot',
            name='tahmin_erp_toplam_negatif_degil',
        ),
        migrations.RemoveConstraint(
            model_name='erpsnapshot',
            name='tahmin_erp_kullanilabilir_negatif_degil',
        ),
        migrations.RemoveConstraint(
            model_name='erpsnapshot',
            name='tahmin_erp_minimum_negatif_degil',
        ),
        migrations.RemoveConstraint(
            model_name='erpsnapshot',
            name='tahmin_erp_tedarik_negatif_degil',
        ),
        migrations.AddField(
            model_name='erpsnapshot',
            name='stok_durumu',
            field=models.CharField(choices=[('MEVCUT', 'Mevcut'), ('KAYIT_YOK', 'Kayıt yok')], default='MEVCUT', max_length=10),
        ),
        migrations.AlterField(
            model_name='erpsnapshot',
            name='kullanilabilir_stok',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='erpsnapshot',
            name='minimum_stok',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='erpsnapshot',
            name='tedarik_gun',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='erpsnapshot',
            name='toplam_stok',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('toplam_stok__isnull', True), ('toplam_stok__gte', 0), _connector='OR'), name='tahmin_erp_toplam_negatif_degil'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('kullanilabilir_stok__isnull', True), ('kullanilabilir_stok__gte', 0), _connector='OR'), name='tahmin_erp_kullanilabilir_negatif_degil'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_stok__isnull', True), ('minimum_stok__gte', 0), _connector='OR'), name='tahmin_erp_minimum_negatif_degil'),
        ),
        migrations.AddConstraint(
            model_name='erpsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('tedarik_gun__isnull', True), ('tedarik_gun__gte', 0), _connector='OR'), name='tahmin_erp_tedarik_negatif_degil'),
        ),
    ]
