# Generated by Django 5.2.17 on 2026-08-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahminler', '0003_remove_erpsnapshot_tahmin_erp_toplam_negatif_degil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakimKarariSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_surumu', models.CharField(max_length=100)),
                ('teknik_aciliyet_skoru', models.FloatField()),
                ('tedarik_riski_skoru', models.FloatField()),
                ('nihai_oncelik_skoru', models.FloatField()),
                ('oncelik_seviyesi', models.CharField(choices=[('DUSUK', 'Düşük'), ('ORTA', 'Orta'), ('YUKSEK', 'Yüksek'), ('KRITIK', 'Kritik')], max_length=10)),
                ('ana_aksiyon', models.CharField(choices=[('IZLEMEYE_DEVAM', 'İzlemeye devam'), ('PLANLI_KONTROL', 'Planlı kontrol'), ('TEKNIK_INCELEME', 'Teknik inceleme'), ('ONCELIKLI_BAKIM_PLANLA', 'Öncelikli bakım planla'), ('ACIL_TEKNIK_DEGERLENDIRME', 'Acil teknik değerlendirme'), ('STOK_VERISINI_DOGRULA', 'Stok verisini doğrula'), ('TEDARIK_SURECINI_BASLAT', 'Tedarik sürecini başlat')], max_length=32)),
                ('ana_ariza_tipi', models.CharField(choices=[('TWF', 'TWF'), ('HDF', 'HDF'), ('PWF', 'PWF'), ('OSF', 'OSF')], max_length=3, null=True)),
                ('karar_guveni', models.CharField(choices=[('YUKSEK', 'Yüksek'), ('ORTA', 'Orta'), ('DUSUK', 'Düşük')], max_length=10)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('tahmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bakim_karari', to='tahminler.tahminkaydi')),
            ],
            options={
                'db_table': 'bakim_karari_snapshotlari',
            },
        ),
        migrations.CreateModel(
            name='KararAksiyonuSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksiyon', models.CharField(choices=[('IZLEMEYE_DEVAM', 'İzlemeye devam'), ('PLANLI_KONTROL', 'Planlı kontrol'), ('TEKNIK_INCELEME', 'Teknik inceleme'), ('ONCELIKLI_BAKIM_PLANLA', 'Öncelikli bakım planla'), ('ACIL_TEKNIK_DEGERLENDIRME', 'Acil teknik değerlendirme'), ('STOK_VERISINI_DOGRULA', 'Stok verisini doğrula'), ('TEDARIK_SURECINI_BASLAT', 'Tedarik sürecini başlat')], max_length=32)),
                ('sira', models.PositiveSmallIntegerField()),
                ('karar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destekleyici_aksiyonlar', to='tahminler.bakimkararisnapshot')),
            ],
            options={
                'db_table': 'karar_aksiyonu_snapshotlari',
                'ordering': ('sira', 'aksiyon'),
            },
        ),
        migrations.CreateModel(
            name='KararGerekcesiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50)),
                ('mesaj_snapshot', models.CharField(max_length=300)),
                ('etki', models.CharField(choices=[('ARTIRDI', 'Artırdı'), ('AZALTTI', 'Azalttı'), ('NOTR', 'Nötr')], max_length=10)),
                ('puan_etkisi', models.FloatField(null=True)),
                ('sira', models.PositiveSmallIntegerField()),
                ('karar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerekceler', to='tahminler.bakimkararisnapshot')),
            ],
            options={
                'db_table': 'karar_gerekcesi_snapshotlari',
                'ordering': ('sira', 'kod'),
            },
        ),
        migrations.CreateModel(
            name='KararUyarisiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50)),
                ('mesaj_snapshot', models.CharField(max_length=300)),
                ('sira', models.PositiveSmallIntegerField()),
                ('karar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uyarilar', to='tahminler.bakimkararisnapshot')),
            ],
            options={
                'db_table': 'karar_uyarisi_snapshotlari',
                'ordering': ('sira', 'kod'),
            },
        ),
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('teknik_aciliyet_skoru__gte', 0), ('teknik_aciliyet_skoru__lte', 100)), name='karar_teknik_skor_0_100'),
        ),
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('tedarik_riski_skoru__gte', 0), ('tedarik_riski_skoru__lte', 100)), name='karar_tedarik_skor_0_100'),
        ),
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('nihai_oncelik_skoru__gte', 0), ('nihai_oncelik_skoru__lte', 100)), name='karar_nihai_skor_0_100'),
        ),
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('ana_ariza_tipi__isnull', True), ('ana_ariza_tipi__in', ('HDF', 'PWF', 'OSF')), _connector='OR'), name='karar_ana_ariza_guvenilir'),
        ),
        migrations.AddConstraint(
            model_name='kararaksiyonusnapshot',
            constraint=models.UniqueConstraint(fields=('karar', 'sira'), name='karar_aksiyon_sira_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='kararaksiyonusnapshot',
            constraint=models.UniqueConstraint(fields=('karar', 'aksiyon'), name='karar_aksiyon_kod_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='kararaksiyonusnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('sira__gte', 1)), name='karar_aksiyon_sira_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='karargerekcesisnapshot',
            constraint=models.UniqueConstraint(fields=('karar', 'sira'), name='karar_gerekce_sira_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='karargerekcesisnapshot',
            constraint=models.UniqueConstraint(fields=('karar', 'kod'), name='karar_gerekce_kod_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='karargerekcesisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('sira__gte', 1)), name='karar_gerekce_sira_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='kararuyarisisnapshot',
            constraint=models.UniqueConstraint(fields=('karar', 'sira'), name='karar_uyari_sira_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='kararuyarisisnapshot',
            constraint=models.UniqueConstraint(fields=('karar', 'kod'), name='karar_uyari_kod_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='kararuyarisisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('sira__gte', 1)), name='karar_uyari_sira_pozitif'),
        ),
    ]
