# Generated by Django 5.2.17 on 2026-08-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahminler', '0004_bakimkararisnapshot_kararaksiyonusnapshot_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('oncelik_seviyesi__in', ('DUSUK', 'ORTA', 'YUKSEK', 'KRITIK'))), name='karar_oncelik_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('ana_aksiyon__in', ('IZLEMEYE_DEVAM', 'PLANLI_KONTROL', 'TEKNIK_INCELEME', 'ONCELIKLI_BAKIM_PLANLA', 'ACIL_TEKNIK_DEGERLENDIRME', 'STOK_VERISINI_DOGRULA', 'TEDARIK_SURECINI_BASLAT'))), name='karar_ana_aksiyon_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='bakimkararisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('karar_guveni__in', ('YUKSEK', 'ORTA', 'DUSUK'))), name='karar_guveni_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='kararaksiyonusnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('aksiyon__in', ('IZLEMEYE_DEVAM', 'PLANLI_KONTROL', 'TEKNIK_INCELEME', 'ONCELIKLI_BAKIM_PLANLA', 'ACIL_TEKNIK_DEGERLENDIRME', 'STOK_VERISINI_DOGRULA', 'TEDARIK_SURECINI_BASLAT'))), name='karar_destek_aksiyon_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='karargerekcesisnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('etki__in', ('ARTIRDI', 'AZALTTI', 'NOTR'))), name='karar_gerekce_etki_gecerli'),
        ),
    ]
