# Generated by Django 5.2.17 on 2026-08-18 20:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bakim", "0003_bakimisemri_isemriolayi_and_more"),
        ("tahminler", "0005_bakimkararisnapshot_karar_oncelik_gecerli_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReplayOturumu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "replay_numarasi",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("HAZIR", "Hazır"),
                            ("CALISIYOR", "Çalışıyor"),
                            ("DURAKLATILDI", "Duraklatıldı"),
                            ("TAMAMLANDI", "Tamamlandı"),
                            ("IPTAL_EDILDI", "İptal edildi"),
                            ("HATALI", "Hatalı"),
                        ],
                        default="HAZIR",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("politika_surumu", models.CharField(max_length=100)),
                ("kaynak_veri_seti", models.CharField(max_length=100)),
                ("prepared_sha256", models.CharField(max_length=64)),
                ("split", models.CharField(max_length=12)),
                ("baslangic_ofseti", models.PositiveIntegerField(default=0)),
                ("toplam_oge", models.PositiveIntegerField()),
                ("varsayilan_batch_boyutu", models.PositiveSmallIntegerField()),
                ("sanal_aralik_saniye", models.PositiveIntegerField()),
                ("makine_esleme_politikasi", models.CharField(max_length=32)),
                (
                    "hata_politikasi",
                    models.CharField(default="HATADA_DEVAM", max_length=20),
                ),
                ("adim_aktif", models.BooleanField(default=False)),
                ("aktif_claim_token", models.UUIDField(null=True)),
                ("olusturulma_zamani", models.DateTimeField(auto_now_add=True)),
                ("baslatilma_zamani", models.DateTimeField(null=True)),
                ("duraklatilma_zamani", models.DateTimeField(null=True)),
                ("tamamlanma_zamani", models.DateTimeField(null=True)),
                ("iptal_zamani", models.DateTimeField(null=True)),
                ("iptal_nedeni", models.CharField(max_length=500, null=True)),
                ("son_islem_zamani", models.DateTimeField(null=True)),
                (
                    "makine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replay_oturumlari",
                        to="bakim.makine",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replay_oturumlari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "replay_oturumlari",
            },
        ),
        migrations.CreateModel(
            name="ReplayOlayi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "olay_tipi",
                    models.CharField(
                        choices=[
                            ("OTURUM_OLUSTURULDU", "Oturum oluşturuldu"),
                            ("BASLATILDI", "Başlatıldı"),
                            ("DURAKLATILDI", "Duraklatıldı"),
                            ("DEVAM_ETTIRILDI", "Devam ettirildi"),
                            ("OGELER_ISLENDI", "Öğeler işlendi"),
                            ("IPTAL_EDILDI", "İptal edildi"),
                            (
                                "BASARISIZLAR_YENIDEN_HAZIRLANDI",
                                "Başarısızlar yeniden hazırlandı",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("gerceklestiren_username_snapshot", models.CharField(max_length=150)),
                ("trace_id", models.CharField(max_length=64)),
                ("onceki_durum", models.CharField(max_length=16, null=True)),
                ("yeni_durum", models.CharField(max_length=16)),
                ("version", models.PositiveIntegerField()),
                ("ilk_sira", models.PositiveIntegerField(null=True)),
                ("son_sira", models.PositiveIntegerField(null=True)),
                ("basarili_sayisi", models.PositiveIntegerField(default=0)),
                ("basarisiz_sayisi", models.PositiveIntegerField(default=0)),
                ("mesaj", models.CharField(max_length=300, null=True)),
                ("olusturulma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "gerceklestiren",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replay_olaylari",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="olaylar",
                        to="tahminler.replayoturumu",
                    ),
                ),
            ],
            options={
                "db_table": "replay_olaylari",
                "ordering": ("olusturulma_zamani", "id"),
            },
        ),
        migrations.CreateModel(
            name="ReplayOgesi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sira", models.PositiveIntegerField()),
                ("kaynak_satir_kimligi", models.PositiveIntegerField()),
                ("external_machine_id", models.CharField(max_length=50)),
                ("sanal_timestamp", models.DateTimeField()),
                ("sensor_snapshot", models.JSONField()),
                ("ground_truth_snapshot", models.JSONField()),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("BEKLIYOR", "Bekliyor"),
                            ("ISLENIYOR", "İşleniyor"),
                            ("BASARILI", "Başarılı"),
                            ("BASARISIZ", "Başarısız"),
                            ("ATLANDI", "Atlandı"),
                        ],
                        default="BEKLIYOR",
                        max_length=12,
                    ),
                ),
                ("deneme_sayisi", models.PositiveSmallIntegerField(default=0)),
                ("islem_baslangic_zamani", models.DateTimeField(null=True)),
                ("tamamlanma_zamani", models.DateTimeField(null=True)),
                ("hata_kodu", models.CharField(max_length=64, null=True)),
                ("hata_mesaji", models.CharField(max_length=300, null=True)),
                ("trace_id", models.CharField(max_length=64, null=True)),
                ("processing_token", models.UUIDField(null=True)),
                ("islem_suresi_ms", models.FloatField(null=True)),
                ("olusturulma_zamani", models.DateTimeField(auto_now_add=True)),
                (
                    "tahmin_kaydi",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replay_ogesi",
                        to="tahminler.tahminkaydi",
                    ),
                ),
                (
                    "oturum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogeler",
                        to="tahminler.replayoturumu",
                    ),
                ),
            ],
            options={
                "db_table": "replay_ogeleri",
                "ordering": ("sira",),
            },
        ),
        migrations.AddConstraint(
            model_name="replayoturumu",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "durum__in",
                        (
                            "HAZIR",
                            "CALISIYOR",
                            "DURAKLATILDI",
                            "TAMAMLANDI",
                            "IPTAL_EDILDI",
                            "HATALI",
                        ),
                    )
                ),
                name="replay_durum_gecerli",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayoturumu",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="replay_version_pozitif"
            ),
        ),
        migrations.AddConstraint(
            model_name="replayoturumu",
            constraint=models.CheckConstraint(
                condition=models.Q(("toplam_oge__gte", 1), ("toplam_oge__lte", 1000)),
                name="replay_toplam_1_1000",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayoturumu",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("varsayilan_batch_boyutu__gte", 1),
                    ("varsayilan_batch_boyutu__lte", 25),
                ),
                name="replay_batch_1_25",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayolayi",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "olay_tipi__in",
                        (
                            "OTURUM_OLUSTURULDU",
                            "BASLATILDI",
                            "DURAKLATILDI",
                            "DEVAM_ETTIRILDI",
                            "OGELER_ISLENDI",
                            "IPTAL_EDILDI",
                            "BASARISIZLAR_YENIDEN_HAZIRLANDI",
                        ),
                    )
                ),
                name="replay_olay_tipi_gecerli",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayolayi",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="replay_olay_version_pozitif",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayolayi",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ilk_sira__isnull", True), ("ilk_sira__gte", 1), _connector="OR"
                ),
                name="replay_olay_ilk_sira_pozitif",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayolayi",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("son_sira__isnull", True), ("son_sira__gte", 1), _connector="OR"
                ),
                name="replay_olay_son_sira_pozitif",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayogesi",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "durum__in",
                        ("BEKLIYOR", "ISLENIYOR", "BASARILI", "BASARISIZ", "ATLANDI"),
                    )
                ),
                name="replay_oge_durum_gecerli",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayogesi",
            constraint=models.UniqueConstraint(
                fields=("oturum", "sira"), name="replay_oge_sira_benzersiz"
            ),
        ),
        migrations.AddConstraint(
            model_name="replayogesi",
            constraint=models.UniqueConstraint(
                fields=("oturum", "kaynak_satir_kimligi"),
                name="replay_oge_kaynak_benzersiz",
            ),
        ),
        migrations.AddConstraint(
            model_name="replayogesi",
            constraint=models.CheckConstraint(
                condition=models.Q(("sira__gte", 1)), name="replay_oge_sira_pozitif"
            ),
        ),
        migrations.AddConstraint(
            model_name="replayogesi",
            constraint=models.CheckConstraint(
                condition=models.Q(("deneme_sayisi__gte", 0)),
                name="replay_deneme_negatif_degil",
            ),
        ),
    ]
