# Generated by Django 5.2.17 on 2026-08-18 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahminler', '0006_replayoturumu_replayolayi_replayogesi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TahminReddi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_nedeni', models.CharField(blank=True, max_length=500, null=True)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('reddeden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahmin_redleri', to=settings.AUTH_USER_MODEL)),
                ('tahmin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='red_bilgisi', to='tahminler.tahminkaydi')),
            ],
            options={
                'db_table': 'tahmin_redleri',
            },
        ),
    ]
