# Generated by Django 5.2.17 on 2026-08-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
                ('parca_kodu', models.CharField(max_length=50, unique=True, verbose_name='parça kodu')),
                ('ad', models.CharField(max_length=150, verbose_name='ad')),
                ('aciklama', models.TextField(blank=True, verbose_name='açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'parça',
                'verbose_name_plural': 'parçalar',
                'db_table': 'parcalar',
                'ordering': ('parca_kodu',),
            },
        ),
        migrations.CreateModel(
            name='Makine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
                ('makine_kodu', models.CharField(max_length=50, unique=True, verbose_name='makine kodu')),
                ('ad', models.CharField(max_length=150, verbose_name='ad')),
                ('tip', models.CharField(max_length=100, verbose_name='tip')),
                ('kritiklik', models.PositiveSmallIntegerField(verbose_name='kritiklik')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
            ],
            options={
                'verbose_name': 'makine',
                'verbose_name_plural': 'makineler',
                'db_table': 'makineler',
                'ordering': ('makine_kodu',),
                'constraints': [models.CheckConstraint(condition=models.Q(('kritiklik__gte', 1), ('kritiklik__lte', 5)), name='makine_kritiklik_1_5')],
            },
        ),
        migrations.CreateModel(
            name='ArizaParcaKurali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
                ('ariza_tipi', models.CharField(choices=[('TWF', 'Takım aşınması arızası'), ('HDF', 'Isı dağılımı arızası'), ('PWF', 'Güç arızası'), ('OSF', 'Aşırı zorlanma arızası'), ('RNF', 'Rastgele arıza')], max_length=3, verbose_name='arıza tipi')),
                ('onerilen_aksiyon', models.TextField(verbose_name='önerilen aksiyon')),
                ('aktif', models.BooleanField(default=True, verbose_name='aktif')),
                ('parca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ariza_kurallari', to='bakim.parca', verbose_name='parça')),
            ],
            options={
                'verbose_name': 'arıza-parça kuralı',
                'verbose_name_plural': 'arıza-parça kuralları',
                'db_table': 'ariza_parca_kurallari',
                'indexes': [models.Index(fields=['ariza_tipi', 'aktif'], name='ariza_tipi_aktif_idx')],
                'constraints': [models.UniqueConstraint(fields=('ariza_tipi', 'parca'), name='ariza_parca_cifti_benzersiz'), models.UniqueConstraint(condition=models.Q(('parca__isnull', True)), fields=('ariza_tipi',), name='ariza_genel_kural_benzersiz')],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='güncellenme tarihi')),
                ('adet', models.PositiveIntegerField(default=0, verbose_name='adet')),
                ('minimum_stok', models.PositiveIntegerField(default=0, verbose_name='minimum stok')),
                ('tedarik_gun', models.PositiveIntegerField(default=0, verbose_name='tedarik günü')),
                ('parca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stok', to='bakim.parca', verbose_name='parça')),
            ],
            options={
                'verbose_name': 'stok',
                'verbose_name_plural': 'stoklar',
                'db_table': 'stoklar',
                'constraints': [models.CheckConstraint(condition=models.Q(('adet__gte', 0)), name='stok_adet_negatif_degil'), models.CheckConstraint(condition=models.Q(('minimum_stok__gte', 0)), name='stok_minimum_negatif_degil'), models.CheckConstraint(condition=models.Q(('tedarik_gun__gte', 0)), name='stok_tedarik_gun_negatif_degil')],
            },
        ),
    ]
