# Generated by Django 5.2.17 on 2026-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizaparcakurali',
            name='gerekli_miktar',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='arizaparcakurali',
            name='tercih_sirasi',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='arizaparcakurali',
            constraint=models.CheckConstraint(condition=models.Q(('gerekli_miktar__gt', 0)), name='ariza_kural_miktar_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='arizaparcakurali',
            constraint=models.CheckConstraint(condition=models.Q(('tercih_sirasi__gt', 0)), name='ariza_kural_sira_pozitif'),
        ),
    ]
