# Generated by Django 5.2.17 on 2026-08-18 19:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakim', '0002_arizaparcakurali_gerekli_miktar_and_more'),
        ('tahminler', '0005_bakimkararisnapshot_karar_oncelik_gecerli_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BakimIsEmri',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_emri_numarasi', models.CharField(editable=False, max_length=32, unique=True)),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('ATANDI', 'Atandı'), ('DEVAM_EDIYOR', 'Devam ediyor'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal edildi')], default='ACIK', max_length=16)),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField(max_length=2000)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('payload_fingerprint', models.CharField(max_length=64)),
                ('politika_surumu', models.CharField(max_length=100)),
                ('kaynak_motor_surumu', models.CharField(max_length=100)),
                ('kaynak_teknik_aciliyet_skoru', models.FloatField()),
                ('kaynak_tedarik_riski_skoru', models.FloatField()),
                ('kaynak_nihai_oncelik_skoru', models.FloatField()),
                ('kaynak_oncelik_seviyesi', models.CharField(max_length=10)),
                ('kaynak_ana_aksiyon', models.CharField(max_length=32)),
                ('kaynak_karar_guveni', models.CharField(max_length=10)),
                ('kaynak_ana_ariza_tipi', models.CharField(max_length=3, null=True)),
                ('etkin_oncelik_seviyesi', models.CharField(max_length=10)),
                ('manuel_oncelik_override', models.BooleanField(default=False)),
                ('override_nedeni', models.CharField(max_length=500, null=True)),
                ('hedef_mudahale_zamani', models.DateTimeField()),
                ('planlanan_baslangic_zamani', models.DateTimeField(null=True)),
                ('gercek_baslangic_zamani', models.DateTimeField(null=True)),
                ('tamamlanma_zamani', models.DateTimeField(null=True)),
                ('iptal_zamani', models.DateTimeField(null=True)),
                ('tamamlama_notu', models.TextField(max_length=2000, null=True)),
                ('iptal_nedeni', models.CharField(max_length=500, null=True)),
                ('bekleme_nedeni', models.CharField(max_length=500, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
                ('atanan_kullanici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atanan_is_emirleri', to=settings.AUTH_USER_MODEL)),
                ('makine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bakim_is_emirleri', to='bakim.makine')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olusturdugu_is_emirleri', to=settings.AUTH_USER_MODEL)),
                ('tahmin_kaydi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_emirleri', to='tahminler.tahminkaydi')),
            ],
            options={
                'db_table': 'bakim_is_emirleri',
            },
        ),
        migrations.CreateModel(
            name='IsEmriOlayi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('olay_tipi', models.CharField(choices=[('OLUSTURULDU', 'Oluşturuldu'), ('ATANDI', 'Atandı'), ('DURUM_DEGISTI', 'Durum değişti'), ('BEKLEMEYE_ALINDI', 'Beklemeye alındı'), ('DEVAM_ETTIRILDI', 'Devam ettirildi'), ('TAMAMLANDI', 'Tamamlandı'), ('IPTAL_EDILDI', 'İptal edildi'), ('ONCELIK_OVERRIDE_EDILDI', 'Öncelik değiştirildi')], max_length=32)),
                ('onceki_durum', models.CharField(max_length=16, null=True)),
                ('yeni_durum', models.CharField(max_length=16)),
                ('gerceklestiren_username_snapshot', models.CharField(max_length=150)),
                ('trace_id', models.CharField(max_length=64)),
                ('aciklama_snapshot', models.CharField(max_length=2000, null=True)),
                ('onceki_atanan_username_snapshot', models.CharField(max_length=150, null=True)),
                ('yeni_atanan_username_snapshot', models.CharField(max_length=150, null=True)),
                ('onceki_oncelik', models.CharField(max_length=10, null=True)),
                ('yeni_oncelik', models.CharField(max_length=10, null=True)),
                ('version', models.PositiveIntegerField()),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
                ('gerceklestiren', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_emri_olaylari', to=settings.AUTH_USER_MODEL)),
                ('is_emri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olaylar', to='bakim.bakimisemri')),
            ],
            options={
                'db_table': 'bakim_is_emri_olaylari',
                'ordering': ('version', 'olusturulma_zamani', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='bakimisemri',
            constraint=models.UniqueConstraint(fields=('olusturan', 'idempotency_key'), name='is_emri_idempotency_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='bakimisemri',
            constraint=models.UniqueConstraint(condition=models.Q(('durum__in', ('ACIK', 'ATANDI', 'DEVAM_EDIYOR', 'BEKLEMEDE'))), fields=('tahmin_kaydi',), name='tahmin_aktif_is_emri_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='bakimisemri',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='is_emri_version_pozitif'),
        ),
        migrations.AddConstraint(
            model_name='bakimisemri',
            constraint=models.CheckConstraint(condition=models.Q(('durum__in', ('ACIK', 'ATANDI', 'DEVAM_EDIYOR', 'BEKLEMEDE', 'TAMAMLANDI', 'IPTAL_EDILDI'))), name='is_emri_durum_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='bakimisemri',
            constraint=models.CheckConstraint(condition=models.Q(('kaynak_oncelik_seviyesi__in', ('DUSUK', 'ORTA', 'YUKSEK', 'KRITIK'))), name='is_emri_kaynak_oncelik_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='bakimisemri',
            constraint=models.CheckConstraint(condition=models.Q(('etkin_oncelik_seviyesi__in', ('DUSUK', 'ORTA', 'YUKSEK', 'KRITIK'))), name='is_emri_etkin_oncelik_gecerli'),
        ),
        migrations.AddConstraint(
            model_name='isemriolayi',
            constraint=models.UniqueConstraint(fields=('is_emri', 'version'), name='is_emri_olay_version_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='isemriolayi',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='is_emri_olay_version_pozitif'),
        ),
    ]
